[package]
name = "ember"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
more-asserts = "0.3.1"
num-traits = "0.2.17"
rustyline = "13.0.0"
